GET http://localhost:5292/customers

###
GET http://localhost:5292/customers/4

###
POST http://localhost:5292/customers
Content-Type: application/json

{
    "FirstName": "Clayton",
    "LastName": "Bonnett",
    "Address": "1111 Airport Rd",
    "Email": "wgml@email.com",
    "TrachType": "cuffless"
}

###
PUT http://localhost:5292/customers/3
Content-Type: application/json

{
    "FirstName": "Nikko",
    "LastName": "Green",
    "Address": "3344 Steele Creek Rd",
    "Email": "sgreen@email.com",
    "TrachType": "cuffed"
}

###
DELETE http://localhost:5292/customers/3